config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  root to: "books#top"
  get "books" => "books#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookers_controller.rb
class BookersController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end


  def create
    @book = Book.new(book_params)
    if @book.save
     flash[:notice] = "Book was successfully created."
     redirect_to booker_path(@book.id)
    else
      @books = Book.all
     render :index
    end
  end


  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    if @book.save
     flash[:notice] = "Book was successfully created."
     redirect_to booker_path(@book.id)
    else
     render bookers_path
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to bookers_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end


  def create
    @book = Book.new(book_params)
    if @book.save
     flash[:notice] = "Book was successfully created."
     redirect_to books_path(@book.id)
    else
      @books = Book.all
     render :index
    end
  end


  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    if @book.save
     flash[:notice] = "Book was successfully created."
     redirect_to books_path(@book.id)
    else
     render books_path
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookers_helper.rb
module BookersHelper
end

app/views/bookers/index.html.erb
<h3>Books</h3>

<table>
<thead>
<tr>
<th>title</th>
<th>body</th>
<th></th>
</tr>
</thead>
<tbody>
<% @books.each do |book| %>
<tr>
<td>
<%= book.title %>
</td>
<td>
<%= book.body %>
</td>
<td>
<%= link_to "show", booker_path(book.id) %>
<%= link_to "edit", edit_booker_path(book.id) %>
<%= link_to "destroy", booker_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %>
</td>
</tr>
<% end %>
</tbody>
</table>


<h1>Newbook</h1>


<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラー
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>



<%= form_with model:@book, url: "/bookers", local: true do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>
  <h4>body</h4>
  <%= f.text_area :body %>
  <br><%= f.submit 'Create Book' %></br>

<% end %>

app/views/bookers/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<%= @book.title %>
<%= @book.body %>

<p><%= link_to "EDIT", edit_booker_path %></p>
<p><%= link_to "BACK", bookers_path %></p>

app/views/bookers/top.html.erb
<h1>ようこそBookersへ!</h1>
<p>Bookers では、さまざまな書籍に関するあなたの意見や
<br>印象を共有し交換することができます</br>
</p>

<p><%= link_to "start", '/bookers' %></p>

app/views/books/edit.html.erb
<h1>編集画面</h1>
<!-- form_with部分 -->
<%= form_with model:@book, url: book_path, local: true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Update Book' %>
<% end %>

<p><%= link_to "SHOW", book_path %></p>
<p><%= link_to "BACK", books_path %></p>

app/views/books/index.html.erb
<h3>Books</h3>

<table>
<thead>
<tr>
<th>title</th>
<th>body</th>
<th></th>
</tr>
</thead>
<tbody>
<% @books.each do |book| %>
<tr>
<td>
<%= book.title %>
</td>
<td>
<%= book.body %>
</td>
<td>
<%= link_to "show", book_path(book.id) %>
<%= link_to "edit", edit_book_path(book.id) %>
<%= link_to "destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %>
</td>
</tr>
<% end %>
</tbody>
</table>


<h1>Newbook</h1>


<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラー
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>



<%= form_with model:@book, url: "/books", local: true do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>
  <h4>body</h4>
  <%= f.text_area :body %>
  <br><%= f.submit 'Create Book' %></br>

<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<%= @book.title %>
<%= @book.body %>

<p><%= link_to "EDIT", edit_book_path %></p>
<p><%= link_to "BACK", books_path %></p>

app/views/books/top.html.erb
<h1>ようこそBookersへ!</h1>
<p>Bookers では、さまざまな書籍に関するあなたの意見や
<br>印象を共有し交換することができます</br>
</p>

<p><%= link_to "start", books_path %></p>

app/views/layouts/_error_messages.html.erb
<% if @book.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>